<?php
/**
 * Central blog post data — used on home page and blogs page.
 * Add new posts to the top of this array.
 */
$blog_posts = [
    [
        'slug'     => 'ai-web-design-2025',
        'title'    => 'How AI is Revolutionising Web Design in 2025',
        'excerpt'  => 'From AI-generated layouts to intelligent UX personalisation — discover how machine learning tools are reshaping the way designers create digital experiences.',
        'image'    => 'https://picsum.photos/seed/aiweb2025/600/380',
        'cat_key'  => 'ai',
        'cat_label'=> 'AI &amp; Design',
        'date'     => 'May 28, 2025',
        'read'     => '5 min read',
    ],
    [
        'slug'     => 'web-dev-trends-2025',
        'title'    => 'Top 10 Web Development Trends to Watch in 2025',
        'excerpt'  => 'Edge computing, server components, WebAssembly and AI-assisted coding — the technologies redefining how modern web applications are built and deployed.',
        'image'    => 'https://picsum.photos/seed/webdev25/600/380',
        'cat_key'  => 'dev',
        'cat_label'=> 'Web Development',
        'date'     => 'May 15, 2025',
        'read'     => '7 min read',
    ],
    [
        'slug'     => 'modern-css-features',
        'title'    => 'Modern CSS Features Every Web Designer Should Know',
        'excerpt'  => 'CSS Container Queries, :has() selector, Cascade Layers and View Transitions — a practical guide to the modern CSS features transforming front-end design.',
        'image'    => 'https://picsum.photos/seed/cssmodern/600/380',
        'cat_key'  => 'design',
        'cat_label'=> 'UI/UX Design',
        'date'     => 'Apr 30, 2025',
        'read'     => '6 min read',
    ],
    [
        'slug'     => 'ai-powered-react-apps',
        'title'    => 'Building AI-Powered Web Apps with React &amp; Next.js',
        'excerpt'  => 'Integrating OpenAI APIs, streaming responses and building intelligent interfaces — a hands-on guide to adding real AI capabilities to your React applications.',
        'image'    => 'https://picsum.photos/seed/reactai25/600/380',
        'cat_key'  => 'tech',
        'cat_label'=> 'Technology',
        'date'     => 'Apr 12, 2025',
        'read'     => '8 min read',
    ],
    [
        'slug'     => 'local-seo-hyderabad',
        'title'    => 'Local SEO in 2025: How to Rank #1 in Hyderabad',
        'excerpt'  => 'Google Business Profile optimisation, local citations, review strategies and geo-targeted content — everything a Hyderabad business needs to dominate local search.',
        'image'    => 'https://picsum.photos/seed/localseo25/600/380',
        'cat_key'  => 'seo',
        'cat_label'=> 'SEO',
        'date'     => 'Mar 24, 2025',
        'read'     => '6 min read',
    ],
    [
        'slug'     => 'figma-to-code-workflow',
        'title'    => 'Figma to Code: The Designer–Developer Handoff in 2025',
        'excerpt'  => 'Auto Layout, variables, dev mode and component annotations — how modern Figma workflows eliminate the gap between design intent and production code.',
        'image'    => 'https://picsum.photos/seed/figmacode25/600/380',
        'cat_key'  => 'design',
        'cat_label'=> 'UI/UX Design',
        'date'     => 'Mar 10, 2025',
        'read'     => '5 min read',
    ],
    [
        'slug'     => 'laravel-api-best-practices',
        'title'    => 'Laravel REST API Best Practices for 2025',
        'excerpt'  => 'Authentication with Sanctum, API versioning, resource transformers, rate limiting and testing strategies — building APIs in Laravel the right way.',
        'image'    => 'https://picsum.photos/seed/laravelapi25/600/380',
        'cat_key'  => 'dev',
        'cat_label'=> 'Web Development',
        'date'     => 'Feb 20, 2025',
        'read'     => '9 min read',
    ],
    [
        'slug'     => 'mobile-ux-2025',
        'title'    => 'Mobile UX Principles That Drive Downloads &amp; Retention',
        'excerpt'  => 'Thumb-friendly navigation, skeleton screens, haptic feedback and micro-interactions — the UX design patterns that separate successful apps from forgettable ones.',
        'image'    => 'https://picsum.photos/seed/mobileuxp25/600/380',
        'cat_key'  => 'tech',
        'cat_label'=> 'Technology',
        'date'     => 'Feb 5, 2025',
        'read'     => '7 min read',
    ],
];
